import shoe from "../../assets/photo/Sneaker.png";

const products = [
  {
    id: 1,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 2,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 3,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 4,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 5,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 6,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 7,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 8,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 9,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 10,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 11,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 12,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 13,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 14,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
  {
    id: 15,
    name: "Sneaker X",
    category: "Sneaker Style",
    price: "$170.00",
    shipping: "Free Shipping",
    image: shoe,
  },
];

export default products;
